#!/usr/bin/env bash
# check_parallel_bench.sh — status of parallel benchmark workers, read from their DBs.
#
# Usage:
#   bash scripts/check_parallel_bench.sh              # human-readable table
#   bash scripts/check_parallel_bench.sh --json       # machine-readable, stable keys
#
# Source of truth is each worker's own SQLite DB (bench_runs + bench_results), never its
# log — docs/parallel-bench-runbook.md §"Worker contracts" items 3 and 4. Logs are only
# reported as a size/liveness aid.
#
# Discovery order:
#   1. <data_par>/parallel_run_meta.json — workers[] first, legacy run_ids{} second,
#      and meta.scenarios even when no run id was captured (startup death).
#   2. glob of <data_par>/*/ scenario dirs, so status is checkable without a meta file.
#
# Exit codes (runbook §3 "Monitor"):
#   0  every worker's run is 'completed'
#   1  at least one worker still running (live pid)
#   2  nothing running and no meta file / no scenario dir to report on
#   3  finished-but-incomplete — a worker died, or hit its window budget, without reaching
#      'completed'. A DB status of 'running' whose pid is gone is 3, not 1.
#      Read runbook §4 (resume) before merging.
#   2  is also returned for a bad command-line argument (usage error).
#
# Environment:
#   JEVRAG_DATA_PAR_ROOT  override the data_par root (default <repo>/backend/data_par).
#
# Strictly read-only: opens every DB with sqlite mode=ro and a short busy timeout, never
# writes to data_par. Uses only python3 stdlib (sqlite3 + json) and does NOT need
# backend/.venv, so it stays usable while workers hog the venv and the local models.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_PAR="${JEVRAG_DATA_PAR_ROOT:-$REPO_ROOT/backend/data_par}"

OUTPUT_JSON=0
for arg in "$@"; do
    case "$arg" in
        --json)
            OUTPUT_JSON=1
            ;;
        -h|--help)
            echo "Usage: bash scripts/check_parallel_bench.sh [--json]"
            echo "Reads bench_runs/bench_results from backend/data_par/<scenario>/app.db."
            echo "Exit codes: 0 all completed, 1 still running, 2 nothing to report, 3 dead-incomplete."
            exit 0
            ;;
        *)
            echo "Unknown argument: $arg" >&2
            echo "Usage: bash scripts/check_parallel_bench.sh [--json]" >&2
            exit 2
            ;;
    esac
done

if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 not found on PATH (the status monitor needs its stdlib sqlite3)." >&2
    exit 2
fi

# The whole report is generated by python3 stdlib below; its exit status IS the runbook
# exit code (set -e propagates it), so bash stays a thin arg-parsing wrapper.
python3 - "$DATA_PAR" "$REPO_ROOT" "$OUTPUT_JSON" <<'PY'
"""DB-driven parallel-bench monitor. Prints the report and exits with the runbook code."""
import glob
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone

DATA_PAR = os.path.realpath(sys.argv[1])
REPO_ROOT = sys.argv[2]
AS_JSON = sys.argv[3] == "1"
META_NAME = "parallel_run_meta.json"
BUSY_TIMEOUT_MS = 2000

ALIVE_STATUS = {"queued", "running", "cancelling", "pending"}
DONE_STATUS = "completed"

RUN_COLS = ("id", "status", "progress_done", "progress_total", "progress_stage")


def display(path):
    """Repo-relative when short, absolute otherwise; never fails."""
    if not path:
        return ""
    try:
        rel = os.path.relpath(path, REPO_ROOT)
    except (ValueError, OSError):
        return path
    if rel.startswith(".."):
        return path
    return rel


def pid_alive(pid):
    """True/False, or None when no pid is known."""
    if not isinstance(pid, int) or pid <= 0:
        return None
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return None
    return True


def scan_worker_procs():
    """Live worker processes -> ({realpath(JEVRAG_DATA_DIR): [pids]}, [all pids]).

    Used when the meta file carries no pid (the current launcher does not write one),
    so liveness is still answered from the process table rather than guessed.
    """
    by_dir, all_pids = {}, []
    if not os.path.isdir("/proc"):
        return by_dir, all_pids
    for name in os.listdir("/proc"):
        if not name.isdigit():
            continue
        pid = int(name)
        base = os.path.join("/proc", name)
        try:
            with open(os.path.join(base, "cmdline"), "rb") as fh:
                cmd = fh.read().replace(b"\x00", b" ").decode("utf-8", "replace")
        except OSError:
            continue
        if "run_testbench.py" not in cmd and "bench_resume.py" not in cmd:
            continue
        all_pids.append(pid)
        try:
            with open(os.path.join(base, "environ"), "rb") as fh:
                raw = fh.read()
        except OSError:
            raw = b""
        env_dir = ""
        for kv in raw.split(b"\x00"):
            if kv.startswith(b"JEVRAG_DATA_DIR="):
                env_dir = kv.split(b"=", 1)[1].decode("utf-8", "replace")
        if env_dir:
            by_dir.setdefault(os.path.realpath(env_dir), []).append(pid)
    return by_dir, all_pids


def load_meta(meta_path):
    """Return (meta_dict, error_string). Tolerates a missing/corrupt/stale meta file."""
    if not os.path.isfile(meta_path):
        return {}, ""
    try:
        with open(meta_path, encoding="utf-8") as fh:
            meta = json.load(fh)
    except (OSError, ValueError) as exc:
        return {}, f"unreadable meta file: {exc}"
    if not isinstance(meta, dict):
        return {}, "meta file is not a JSON object"
    return meta, ""


def split_csv(value):
    if not isinstance(value, str):
        return []
    return [part.strip() for part in value.split(",") if part.strip()]


def discover(meta):
    """Build the worker list: meta (authoritative) unioned with data_par/* dirs."""
    entries = {}

    def add(scenario, run_id="", pid=None, data_dir="", source="meta"):
        if not scenario:
            return
        key = scenario
        cur = entries.setdefault(key, {"scenario": key, "run_id": "", "pid": None,
                                       "data_dir": "", "source": source})
        if data_dir:
            cur["data_dir"] = data_dir
        if run_id:
            cur["run_id"] = run_id
        if isinstance(pid, int) and pid > 0:
            cur["pid"] = pid
        if source == "meta":
            cur["source"] = "meta"

    # 1. meta.workers[] — the runbook contract (item 4)
    workers = meta.get("workers")
    if isinstance(workers, list):
        for w in workers:
            if isinstance(w, dict):
                add(w.get("scenario"), w.get("run_id"), w.get("pid"), w.get("data_dir"))

    # 2. legacy meta.run_ids map {scenario: uuid} (written by older launches)
    run_ids = meta.get("run_ids")
    if isinstance(run_ids, dict):
        for scenario, run_id in run_ids.items():
            add(scenario, run_id if isinstance(run_id, str) else "")

    # 3. meta.scenarios — expected set, so a worker that died before printing RUN_ID=
    #    is still reported instead of silently vanishing
    for scenario in split_csv(meta.get("scenarios")):
        add(scenario)

    # 4. fallback: whatever scenario dirs actually exist under data_par
    for path in sorted(glob.glob(os.path.join(DATA_PAR, "*"))):
        if not os.path.isdir(path):
            continue
        scenario = os.path.basename(path)
        has_db = os.path.isfile(os.path.join(path, "app.db"))
        has_log = os.path.isfile(os.path.join(path, "bench.log"))
        if has_db or has_log:
            add(scenario, data_dir=path, source="dir")

    for entry in entries.values():
        if not entry["data_dir"]:
            entry["data_dir"] = os.path.join(DATA_PAR, entry["scenario"])
        if os.path.exists(entry["data_dir"]):
            entry["data_dir"] = os.path.realpath(entry["data_dir"])
    return [entries[k] for k in sorted(entries)]


def read_run(db_path, run_id, scenario):
    """Open one worker DB read-only and pull its run row + scored row count."""
    out = {"db_found": False, "db_error": "", "run_found": False, "run_id": run_id,
           "run_fallback": False,
           "status": "", "progress_done": None, "progress_total": None,
           "progress_stage": "", "result_rows": None, "result_rows_run": None,
           "scenario_ids_in_run": []}
    if not os.path.isfile(db_path):
        return out
    out["db_found"] = True
    try:
        con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True,
                              timeout=BUSY_TIMEOUT_MS / 1000.0)
    except sqlite3.Error as exc:
        out["db_error"] = f"open failed: {exc}"
        return out
    try:
        con.execute(f"PRAGMA busy_timeout={BUSY_TIMEOUT_MS}")
        row = None
        if run_id:
            row = con.execute(
                f"SELECT {', '.join(RUN_COLS)} FROM bench_runs WHERE id = ?",
                (run_id,)).fetchone()
            if row is None:
                # tolerate an abbreviated run id in the meta file
                row = con.execute(
                    f"SELECT {', '.join(RUN_COLS)} FROM bench_runs WHERE id LIKE ? "
                    "ORDER BY created_at DESC LIMIT 1", (f"{run_id}%",)).fetchone()
        if row is None:
            # no run id known (or meta lost it): this DB belongs to exactly one worker,
            # so its newest run row is the one being monitored.
            row = con.execute(
                f"SELECT {', '.join(RUN_COLS)} FROM bench_runs "
                "ORDER BY created_at DESC, rowid DESC LIMIT 1").fetchone()
            if run_id and row is not None:
                out["run_fallback"] = True
        if row is None:
            return out
        out["run_found"] = True
        out["run_id"], out["status"] = row[0], row[1]
        out["progress_done"], out["progress_total"], out["progress_stage"] = row[2], row[3], row[4]
        out["result_rows"] = con.execute(
            "SELECT COUNT(*) FROM bench_results WHERE run_id = ? AND scenario_id = ?",
            (out["run_id"], scenario)).fetchone()[0]
        out["result_rows_run"] = con.execute(
            "SELECT COUNT(*) FROM bench_results WHERE run_id = ?",
            (out["run_id"],)).fetchone()[0]
        out["scenario_ids_in_run"] = [r[0] for r in con.execute(
            "SELECT DISTINCT scenario_id FROM bench_results WHERE run_id = ? LIMIT 8",
            (out["run_id"],)).fetchall()]
    except sqlite3.Error as exc:
        out["db_error"] = str(exc).strip() or "sqlite error"
    finally:
        con.close()
    return out


def size_bytes(path):
    try:
        return os.path.getsize(path)
    except OSError:
        return None


def build_worker(entry, procs_by_dir, all_proc_pids, meta, allow_any_pid=False):
    data_dir = entry["data_dir"]
    db_path = os.path.join(data_dir, "app.db")
    log_file = os.path.join(data_dir, "bench.log")
    info = read_run(db_path, entry["run_id"], entry["scenario"])

    pid, pid_source = entry["pid"], "meta"
    if pid is None:
        found = procs_by_dir.get(os.path.realpath(data_dir)) or []
        if found:
            pid, pid_source = sorted(found)[0], "proc-scan"
        elif allow_any_pid and len(all_proc_pids) == 1:
            # exactly one scenario and one worker process: the mapping is unambiguous
            pid, pid_source = all_proc_pids[0], "proc-scan-only"

    alive = pid_alive(pid)
    status = info["status"]
    notes = []

    if not os.path.isdir(data_dir):
        verdict = "dead_incomplete"
        notes.append("scenario dir missing (worker never started here)")
    elif not info["db_found"]:
        verdict = "running" if alive else "dead_incomplete"
        notes.append("no app.db yet (pre-ingest)" if alive
                     else "no app.db and no live pid — startup death; see its bench.log")
    elif info["db_error"]:
        # unreadable DB: never claim success; a locked/corrupt DB is an operator problem
        verdict = "running" if alive else "dead_incomplete"
        notes.append(f"DB read failed: {info['db_error']}")
    elif not info["run_found"]:
        verdict = "running" if alive else "dead_incomplete"
        notes.append("app.db has no bench_runs row" if alive
                     else "app.db has no bench_runs row and no live pid")
    elif status == DONE_STATUS:
        verdict = "completed"
        if info["result_rows"] == 0:
            notes.append("completed but 0 scored rows for this scenario")
    elif status in ALIVE_STATUS:
        if alive:
            verdict = "running"
        else:
            verdict = "dead_incomplete"
            notes.append(f"DB still says '{status}' but its pid is gone")
    else:
        verdict = "dead_incomplete"
        notes.append(f"terminal status '{status}' — not completed")

    if info["run_found"] and info["run_fallback"]:
        notes.append("meta run_id %s is not in this DB; reporting newest run %s"
                     % (entry["run_id"], info["run_id"]))
        if verdict == "completed" and alive is not True:
            # The launched run id is absent and no worker owns the DB any more: an older
            # completed row in the same file must not read as "this launch finished".
            verdict = "dead_incomplete"
            notes.append("the launched run id is absent from this DB — not evidence "
                         "that this launch completed")
    if alive is None and verdict == "dead_incomplete" and pid is None:
        notes.append("pid unknown (not in meta, no matching worker process)")
    if (info["result_rows"] == 0 and info["result_rows_run"]
            and info["scenario_ids_in_run"]
            and entry["scenario"] not in info["scenario_ids_in_run"]):
        notes.append("run rows belong to scenario id(s): " + ",".join(info["scenario_ids_in_run"]))

    arms = meta.get("arms") or "base,gate-none"
    window = meta.get("window_minutes")
    if info["run_found"] and info["run_id"]:
        hint = (f"bash scripts/run_parallel_bench.sh --scenarios {entry['scenario']} "
                f"--resume {entry['scenario']}:{info['run_id']} --arms {arms}")
        if window is not None:
            hint += f" --window-minutes {window}"
    else:
        hint = (f"bash scripts/run_parallel_bench.sh --scenarios {entry['scenario']} "
                f"--arms {arms}")

    return {
        "scenario": entry["scenario"],
        "source": entry["source"],
        "data_dir": data_dir,
        "db_path": db_path,
        "db_found": info["db_found"],
        "db_error": info["db_error"],
        "run_found": info["run_found"],
        "run_fallback": info["run_fallback"],
        "run_id": info["run_id"],
        "status": status,
        "progress_done": info["progress_done"],
        "progress_total": info["progress_total"],
        "progress_stage": info["progress_stage"],
        "result_rows": info["result_rows"],
        "result_rows_run": info["result_rows_run"],
        "pid": pid,
        "pid_alive": alive,
        "pid_source": pid_source if pid is not None else "",
        "verdict": verdict,
        "log_file": log_file,
        "log_bytes": size_bytes(log_file),
        "note": "; ".join(notes),
        "resume_hint": hint,
    }


def overall(workers, meta_error):
    """Exit code + label per runbook §3.

    An unreadable meta file means the expected worker set cannot be enumerated, so the
    DBs on disk can never add up to 'all clear' — that is exit 3 (read §4/§5 first).
    """
    if not workers:
        return 2, "nothing_to_report"
    if any(w["verdict"] == "running" for w in workers):
        return 1, "running"
    if any(w["verdict"] == "dead_incomplete" for w in workers):
        return 3, "finished_incomplete"
    if all(w["verdict"] == "completed" for w in workers):
        if meta_error:
            return 3, "meta_unreadable"
        return 0, "all_completed"
    return 2, "nothing_to_report"


def progress_str(w):
    done = w["progress_done"]
    total = w["progress_total"]
    if done is None:
        return "-"
    if not total:
        return f"{done}/?"
    return f"{done}/{total}"


def rows_str(w):
    return "-" if w["result_rows"] is None else str(w["result_rows"])


def alive_str(w):
    if w["pid_alive"] is True:
        return "yes"
    if w["pid_alive"] is False:
        return "NO"
    return "?"


def render_human(workers, code, label, meta, meta_path, meta_error):
    lines = []
    bar = "=" * 56
    lines.append(bar)
    lines.append("Parallel Benchmark Status")
    lines.append(bar)
    lines.append(f"Data root : {display(DATA_PAR)}")
    if os.path.isfile(meta_path):
        meta_desc = f"label={meta.get('label', '-')}, arms={meta.get('arms', '-')}"
        if meta_error:
            meta_desc = meta_error
        lines.append(f"Meta file : {display(meta_path)} ({meta_desc})")
    else:
        lines.append(f"Meta file : {display(meta_path)} (absent — using scenario dirs)")
    if meta.get("launched_at"):
        lines.append(f"Launched  : {meta['launched_at']}")
    lines.append("")

    if not workers:
        lines.append("No parallel workers to report on: no meta file and no scenario "
                     "dirs under data_par.")
        lines.append("Launch them with: bash scripts/run_parallel_bench.sh "
                     "--arms base,gate-none --scenarios squad,hotpotqa")
        print("\n".join(lines))
        return

    counts = {"completed": 0, "running": 0, "dead_incomplete": 0}
    for w in workers:
        counts[w["verdict"]] = counts.get(w["verdict"], 0) + 1
    alive_pids = sorted({w["pid"] for w in workers if w["pid_alive"] and w["pid"]})
    lines.append(f"Workers: {len(workers)}  completed: {counts['completed']}  "
                 f"running: {counts['running']}  dead-incomplete: {counts['dead_incomplete']}")
    if alive_pids:
        lines.append(f"Live worker pids: {', '.join(str(p) for p in alive_pids)}")
    lines.append("")

    headers = ("SCENARIO", "STATUS", "PROGRESS", "ROWS", "PID", "ALIVE", "VERDICT")
    table = [headers]
    for w in workers:
        table.append((w["scenario"], w["status"] or "no-run-row", progress_str(w),
                      rows_str(w), "-" if w["pid"] is None else str(w["pid"]),
                      alive_str(w), w["verdict"]))
    widths = [max(len(str(r[i])) for r in table) for i in range(len(headers))]
    for idx, row in enumerate(table):
        text = "  ".join(str(cell).ljust(widths[i]) for i, cell in enumerate(row)).rstrip()
        lines.append(text)
        if idx == 0:
            lines.append("  ".join("-" * width for width in widths))

    lines.append("")
    for w in workers:
        stage = w["progress_stage"] or "-"
        log = display(w["log_file"])
        size = w["log_bytes"]
        log_desc = "missing" if size is None else f"{size} bytes"
        lines.append(f"{w['scenario']}: stage={stage}  log={log} ({log_desc})")
        if w["note"]:
            lines.append(f"    note: {w['note']}")

    lines.append("")
    bad = [w for w in workers if w["verdict"] == "dead_incomplete"]
    if code == 0:
        lines.append("Overall: every worker's run is completed — safe to merge "
                     "(runbook §5).")
    elif code == 1:
        lines.append("Overall: at least one worker is still running — keep monitoring.")
    elif label == "meta_unreadable":
        lines.append("Overall: every DB on disk reads completed, but the meta file is "
                     "unreadable so the launched worker set cannot be confirmed — "
                     "do not merge until it is checked (runbook §4/§5).")
    elif code == 3:
        lines.append(f"Overall: {len(bad)} of {len(workers)} worker(s) finished without "
                     "reaching 'completed' — do NOT merge and call it a full run "
                     "(runbook §4/§5).")
    else:
        lines.append("Overall: nothing running and no meta file to report on.")
    print("\n".join(lines))
    for w in bad:
        print(f"  resume {w['scenario']}:")
        if w["log_bytes"] == 0:
            print(f"    (0-byte log {display(w['log_file'])} = died during startup; "
                  "read it, then relaunch that scenario alone)")
        print(f"    cd {REPO_ROOT} && {w['resume_hint']}")


def main():
    meta_path = os.path.join(DATA_PAR, META_NAME)
    meta, meta_error = load_meta(meta_path)
    procs_by_dir, all_proc_pids = scan_worker_procs()
    entries = discover(meta)
    only_one = len(entries) == 1 and len(all_proc_pids) == 1
    workers = [build_worker(e, procs_by_dir, all_proc_pids, meta, only_one)
               for e in entries]
    code, label = overall(workers, meta_error)

    if AS_JSON:
        payload = {
            "version": 1,
            "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "data_par_root": DATA_PAR,
            "meta_file": meta_path,
            "meta_present": os.path.isfile(meta_path),
            "meta_error": meta_error,
            "label": meta.get("label"),
            "driver": meta.get("driver"),
            "arms": meta.get("arms"),
            "scenarios": meta.get("scenarios"),
            "max_per_scenario": meta.get("max_per_scenario"),
            "window_minutes": meta.get("window_minutes"),
            "launched_at": meta.get("launched_at"),
            "status": label,
            "exit_code": code,
            "summary": {
                "workers": len(workers),
                "completed": sum(1 for w in workers if w["verdict"] == "completed"),
                "running": sum(1 for w in workers if w["verdict"] == "running"),
                "dead_incomplete": sum(1 for w in workers if w["verdict"] == "dead_incomplete"),
                "total_rows": sum(w["result_rows"] or 0 for w in workers),
            },
            "workers": workers,
        }
        print(json.dumps(payload, indent=2, sort_keys=False))
    else:
        render_human(workers, code, label, meta, meta_path, meta_error)
    return code


sys.exit(main())
PY
